### ISSUE TITLE
Extra slots not considered part of the inventory or toolbelt

### ISSUE THREAD

**Issue by DeadlyDad** [KhaineGB/KhaineA20ModletsHarmony#2]
- Ammo placed in the extra slots isn't seen by weapons.
- Clicking on items in extra slots doesn't bring up the info/interaction menu
- Scrolling with the mouse wheel doesn't scroll through extra slots

**Comment by KhaineGB** [comment]
Again, TURN EAC OFF.

Anything that uses a DLL file cannot be ran with EAC on. This issue is an issue because you have EAC on.
